name: Deployment Pipeline

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Root Dependencies
        run: npm install # Installs things like concurrently
      - name: Install Client Dependencies
        run: npm install --prefix client
      - name: Install Server Dependencies
        run: npm install --prefix server
      - name: Run linters
        run: npm run lint
      - name: Run Tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm run test # concurent test one not working
